name: opentelemetry

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Install Rust toolchain
        run: rustup default nightly

      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: All
        run: cargo test --all --all-features

      - name: Docs
        run: cargo doc --all-features

      - name: Build powerset
        run: cargo hack build --feature-powerset --lib

      - name: Test powerset
        run: cargo hack test --feature-powerset --lib

      - name: Minimal versions
        run: cargo hack test --feature-powerset --lib -Z minimal-versions

  integration:
    name: Test (Integration)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 24.x

      - name: Install Rust toolchain
        run: rustup default nightly

      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: Get otelcol
        run: wget -O otelcol.deb https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.107.0/otelcol_0.107.0_linux_amd64.deb

      - name: Install otelcol
        run: sudo dpkg -i ./otelcol.deb

      - name: Integration Test
        working-directory: ./emitter/otlp/test/integration
        run: cargo hack run --feature-powerset
